//******************************************************************************
//* clean.js
//*
//* Defines a custom gulp task for removing all output files that were 
//* autogenerated by other gulp tasks 
//******************************************************************************

const gulp = require("gulp"),
    del = require("del"),
    yargs = require("yargs").argv,
    log = require("fancy-log"),
    colors = require("ansi-colors");

gulp.task('clean', (done) => {

    if (yargs.noclean || yargs.nc) {
        gutil.log(`${gutil.colors.bgWhite(" ")} Skipping clean due to flag.`);
        return done();
    }

    const directories = [
        "./build",
        "./dist",
        "./debugging",
        "./serve",
        "./testing"
    ];

    log(`${colors.bgblue(" ")} Cleaning directories: ${directories.join(", ")}.`);
    del(directories).then(() => {
        log(`${colors.bggreen(" ")} Cleaned directories: ${directories.join(", ")}.`);
        done();
    }).catch(e => {
        log(`${colors.bgred(" ")} Error cleaned directories: ${directories.join(", ")}.`);
        done(e);
    });
});

gulp.task("clean-docs", (done) => {
    del("./docs").then(() => {
        done();
    });
});
