//******************************************************************************
//* clean.js
//*
//* Defines a custom gulp task for removing all output files that were 
//* autogenerated by other gulp tasks 
//******************************************************************************

const gulp = require("gulp"),
    del = require("del"),
    yargs = require("yargs").argv,
    log = require("fancy-log"),
    colors = require("ansi-colors");

gulp.task('clean', (done) => {

    if (yargs.noclean || yargs.nc) {
        log(`${colors.bgWhite(" ")} Skipping clean due to flag.`);
        return done();
    }

    const directories = [
        "./dist",
        "./serve",
        "./site",
    ];

    log(`${colors.bgBlue(" ")} Cleaning directories: ${directories.join(", ")}.`);
    del(directories).then(() => {
        log(`${colors.bgGreen(" ")} Cleaned directories: ${directories.join(", ")}.`);
        done();
    }).catch(e => {
        log(`${colors.bgRed(" ")} Error cleaning directories: ${directories.join(", ")}.`);
        done(e);
    });
});

gulp.task("clean-build", (done) => {
    del("./build").then(() => {
        done();
    });
});

gulp.task("clean-build-debugging", (done) => {
    del("./build/debugging").then(() => {
        done();
    });
});
