name: ❓ Question/Assistance Needed
description: Ask a question or seek guidance
labels: ["type: question", "help wanted 🐇"]

body:
- type: markdown
  attributes:
    value: |
      This issue type is for asking questions or requesting assistance in using the library. Please provide as much information as possible so a member of the community can best assist you. Thanks!

      - Follow our guidance on [How To Create Good Issues](https://github.dev/juliemturner/pnpjs/wiki/How-to-Create-Good-Issues).
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
- type: dropdown
  attributes:
    label: What version of PnPjs library you are using
    options:
      - 4.x
      - 3.x
      - 2.x (No longer supported)
      - 1.x (No longer supported)
    default: 1
  validations:
    required: true
- type: input
  id: minorver
  attributes:
    label: Minor Version Number
    description: Include the minor and patch version numbers, e.g. for 4.1.0 
    placeholder: '1.0'
  validations:
    required: true
- type: dropdown
  attributes:
    label: Target environment
    options:
      - All
      - SharePoint Framework
      - NodeJS
      - Browser App (Hosted external to Microsoft 365 platform)
      - other (enter in the "Additional environment details" area below)
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional environment details
    description: Please describe the environment you're working in and how you're authenticating.
    placeholder: |
      I'm using NodeJS and certificate based MSAL for authentication.
  validations:
    required: true
- type: textarea
  attributes:
    label: Question/Request
    description: Please included details to describe your situation, code fenced example code OR a link to a code snippet using GitHub or CodePen or the like to show how your code is structured and get you the right help more quickly.
    placeholder: |
      I'm struggling to get a list item. Here is the code I'm running. Can anyone help me figure out what's wrong?
      
      ```TypeScript
      import { spfi } from "@pnp/sp";
      import "@pnp/sp/webs";
      import "@pnp/sp/lists";
      import "@pnp/sp/items";

      const sp = spfi(...);

      // get all the items from a list
      const items: any[] = await sp.web.lists.getByTitle("My List").items();
      console.log(items);
      ```
  validations:
    required: true
