import { SPRest } from "../src/rest";

import "../src/appcatalog";
import "../src/attachments";
import "../src/clientsidepages";
import "../src/comments";
import "../src/content-types";
import "../src/features";
import "../src/fields";
import "../src/files";
import "../src/folders";
import "../src/forms";
import "../src/hubsites";
import "../src/items";
import "../src/lists";
import "../src/navigation";
import "../src/profiles";
import "../src/regional-settings";
import "../src/related-items";
import "../src/search";
import "../src/security";
import "../src/sharing";
import "../src/site-designs";
import "../src/site-groups";
import "../src/site-scripts";
import "../src/site-users";
import "../src/sites";
import "../src/social";
import "../src/sputilities";
import "../src/subscriptions";
import "../src/user-custom-actions";
import "../src/views";
import "../src/webparts";
import "../src/webs";

export * from "../src/appcatalog";
export * from "../src/attachments";
export * from "../src/clientsidepages";
export * from "../src/comments";
export * from "../src/content-types";
export * from "../src/features";
export * from "../src/fields";
export * from "../src/files";
export * from "../src/folders";
export * from "../src/forms";
export * from "../src/hubsites";
export * from "../src/items";
export * from "../src/lists";
export * from "../src/navigation";
export * from "../src/profiles";
export * from "../src/regional-settings";
export * from "../src/related-items";
export * from "../src/search";
export * from "../src/security";
export * from "../src/sharing";
export * from "../src/site-designs";
export * from "../src/site-groups";
export * from "../src/site-scripts";
export * from "../src/site-users";
export * from "../src/sites";
export * from "../src/social";
export * from "../src/sputilities";
export * from "../src/subscriptions";
export * from "../src/user-custom-actions";
export * from "../src/views";
export * from "../src/webparts";
export * from "../src/webs";
export * from "../src/sp";

export const sp = new SPRest();
